name: Tag and publish
on:
  push:
    branches:
      - main

jobs:
  update_badges:
    uses: AllenNeuralDynamics/.github/.github/workflows/python_library_template_update_badges_v0_0_1.yml@main
    with:

      app-id: ${{ vars.SEMANTIC_RELEASE_BOT_APP_ID }}

    secrets:

      app-private-key: ${{ secrets.SEMANTIC_RELEASE_BOT_PRIVATE_KEY }}


  tag:
    needs: update_badges
    uses: AllenNeuralDynamics/.github/.github/workflows/python_library_template_tag_v0_0_1.yml@main
    with:

      app-id: ${{ vars.SEMANTIC_RELEASE_BOT_APP_ID }}

    secrets:

      app-private-key: ${{ secrets.SEMANTIC_RELEASE_BOT_PRIVATE_KEY }}


